defmodule AdventOfCode2025.Day07Test do
  use ExUnit.Case, async: true

  alias AdventOfCode2025.Day07

  test "Day07 part A example" do
    assert Day07.part_a(example_input()) == 21
  end

  defp example_input() do
    """
    .......S.......
    ...............
    .......^.......
    ...............
    ......^.^......
    ...............
    .....^.^.^.....
    ...............
    ....^.^...^....
    ...............
    ...^.^...^.^...
    ...............
    ..^...^.....^..
    ...............
    .^.^.^.^.^...^.
    ...............
    """
    |> String.trim()
    |> String.split("\n")
    |> Enum.map(&String.trim/1)
  end

  @tag :skip
  test "Day07 part B example" do
    assert Day07.part_b(example_input()) == 42
  end
end
